### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by roberts1y**
tested & working changes

### CODE REVIEW

**Comment by Sam-Malta** [comment]
Can't approve for some reason get @Charles-M-Hecker and @BechtelLo25

**Review by Sam-Malta — DISMISSED** [review]
Nevermind, looks good

**Review by Sam-Malta — CHANGES_REQUESTED** [review]
Fix conventions m_robotContainer should only be camel case etc then submit for reapproval

**Review by Sam-Malta — APPROVED** [review]
Let's get a system's test to ensure none of the variable changes affect the function of the bot, after that someone can submit their second approval.

**Comment by HaBr24** [comment]
Not a software problem
PCM is being triggered as expected, but the solenoid on the left barrel is not firing. Michael thinks it's a control panel problem.
Pending Mechanical Action

**Comment by HaBr24** [comment]
Not a software problem
PCM is being triggered as expected, but the solenoid on the left barrel is not firing. Michael thinks it's a control panel problem.
Pending Mechanical Action

**Pull request closed without merging**
